/**
 * ===========================================================================
 * Proving the client sends what it claims to send
 * ===========================================================================
 *
 * Target: https://httpbin.org — a request-and-response inspection service. It
 * echoes back exactly what it received and will answer with any status code on
 * demand. Unlimited, and no credentials needed.
 *
 * ---------------------------------------------------------------------------
 * WHY THIS SUITE EXISTS
 * ---------------------------------------------------------------------------
 * Every other suite tests an API *through* the framework. This one tests the
 * framework itself, against a real server rather than a stub.
 *
 * That distinction matters. A stub is written by the same person who wrote the
 * client, so the two can share a misunderstanding and still agree. An echo
 * server is neutral: it reports what genuinely arrived over a real connection,
 * through a real TLS handshake, with real header normalisation applied. If the
 * builder claims to send an idempotency key, this is what proves it does.
 *
 * The bug that prompted several of these: `.text()` with a JSON content type
 * was being re-serialised by the underlying transport, so a body meant to be
 * malformed arrived as valid JSON. The stub could not see it, because the stub
 * received exactly what the transport chose to send. An echo server could.
 */
import { test, expect } from '../../src/fixtures';
import { PUBLIC_APIS } from '../../src/config/environments';
import { EDGE_CASE_STRINGS } from '../../src/utils/data.utils';
import { decodeJwt } from '../../src/auth/jwt';

/** Everything here goes to the echo service, on a derived client. */
test.describe('http client — real-wire behaviour @regression @client', () => {
  test('sends JSON bodies with the right content type @smoke', async ({ http }) => {
    const payload = { name: 'wire check', nested: { list: [1, 2, 3] } };

    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .post('/post')
      .json(payload)
      .as('json echo')
      .send();

    response.expectOk();
    /* `json` is httpbin's parsed view of the body it received — so this
     * asserts the payload survived serialisation intact. */
    expect(response.path('json')).toEqual(payload);
    expect(response.path<string>('headers.Content-Type')).toContain('application/json');
  });

  test('sends form bodies url-encoded', async ({ http }) => {
    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .post('/post')
      .form({ alpha: 'one', beta: 2, gamma: true })
      .as('form echo')
      .send();

    response.expectOk();
    /* Numbers and booleans become strings on the wire — worth asserting,
     * because a test that assumed otherwise would be quietly wrong. */
    expect(response.path('form')).toEqual({ alpha: 'one', beta: '2', gamma: 'true' });
    expect(response.path<string>('headers.Content-Type')).toContain(
      'application/x-www-form-urlencoded',
    );
  });

  test('sends raw text verbatim, without re-encoding it', async ({ http }) => {
    /* The regression test for a real bug. A string body with a JSON content
     * type used to be JSON-serialised by the transport, turning
     * `{ not json` into the valid JSON string `"{ not json"`. The framework
     * now sends text as bytes, so what arrives is what was written. */
    const raw = '{ deliberately not json';

    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .post('/post')
      .text(raw, 'application/json')
      .as('raw text echo')
      .send();

    response.expectOk();
    expect(response.path<string>('data'), 'the body must arrive byte-for-byte').toBe(raw);
    /* And httpbin could not parse it either, which is the whole point. */
    expect(response.path('json')).toBeNull();
  });

  test('sends multipart uploads with fields and files', async ({ http }) => {
    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .post('/post')
      .field('label', 'upload check')
      .fileFromBuffer('document', Buffer.from('file contents here'), 'notes.txt', 'text/plain')
      .as('multipart echo')
      .send();

    response.expectOk();
    expect(response.path('form.label')).toBe('upload check');
    expect(response.path<string>('files.document')).toContain('file contents here');
    /* The boundary is generated by the transport, which is why the builder
     * deliberately removes any content-type header the caller set. */
    expect(response.path<string>('headers.Content-Type')).toContain('multipart/form-data');
    expect(response.path<string>('headers.Content-Type')).toContain('boundary=');
  });

  test('encodes repeated query values as repeated parameters', async ({ http }) => {
    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .get('/get')
      .query({ tag: ['alpha', 'beta'], page: 2, skipped: undefined })
      .arrays('repeat')
      .as('query echo')
      .send();

    response.expectOk();
    expect(response.path('args.tag')).toEqual(['alpha', 'beta']);
    expect(response.path('args.page')).toBe('2');
    /* `undefined` values are dropped rather than sent as the string
     * "undefined" — a genuinely common bug in hand-rolled query builders. */
    expect(response.path('args.skipped')).toBeUndefined();
  });

  test('encodes a comma-joined array when asked to', async ({ http }) => {
    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .get('/get')
      .query({ tag: ['alpha', 'beta'] })
      .arrays('comma')
      .as('comma query echo')
      .send();

    /* Servers disagree about this, and choosing wrong produces a filter that
     * silently matches everything. The builder supports both so the test can
     * match whatever the API under test actually wants. */
    expect(response.path('args.tag')).toBe('alpha,beta');
  });

  test('preserves unicode, emoji and control characters in a body', async ({ http }) => {
    /* Every one of these has broken a real API's encoding handling. Sending
     * them through a neutral echo proves the framework is not the thing that
     * mangles them before they get there. */
    const payload = {
      unicode: EDGE_CASE_STRINGS.unicode,
      emoji: EDGE_CASE_STRINGS.emoji,
      combining: EDGE_CASE_STRINGS.combining,
      rightToLeft: EDGE_CASE_STRINGS.rightToLeft,
      newlines: EDGE_CASE_STRINGS.newlines,
      quote: EDGE_CASE_STRINGS.singleQuote,
    };

    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .post('/post')
      .json(payload)
      .as('unicode echo')
      .send();

    expect(response.path('json')).toEqual(payload);
  });

  /* ================================================================= *
   * CREDENTIALS
   * ================================================================= */

  test('basic auth reaches the server in the right form', async ({ http }) => {
    /* Set per request rather than through a provider, which is the escape
     * hatch for a single call that needs different credentials. */
    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .get('/basic-auth/{user}/{pass}')
      .params({ user: 'framework', pass: 'secret' })
      .basic('framework', 'secret')
      .as('basic auth')
      .send();

    response.expectOk();
    expect(response.path('authenticated')).toBe(true);
    expect(response.path('user')).toBe('framework');
  });

  test('bearer tokens reach the server, and JWT claims can be inspected', async ({ http }) => {
    /* A structurally valid JWT, signed with nothing — the framework decodes
     * claims and never verifies signatures, which is the API's job. */
    const token = [
      Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url'),
      Buffer.from(
        JSON.stringify({ sub: 'user-42', scope: 'orders:read orders:write', exp: 4_102_444_800 }),
      ).toString('base64url'),
      'not-a-real-signature',
    ].join('.');

    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .get('/bearer')
      .bearer(token)
      .as('bearer auth')
      .send();

    response.expectOk();
    expect(response.path('authenticated')).toBe(true);
    expect(response.path('token')).toBe(token);

    /* And the claims the suite would assert on in a real authorisation test. */
    const claims = decodeJwt(token).claims;
    expect(claims.sub).toBe('user-42');
  });

  test('anonymous() suppresses credentials so the 401 path can be tested', async ({ http }) => {
    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .get('/bearer')
      .anonymous()
      .expectStatus(401)
      .as('unauthenticated')
      .send();

    expect(response).toHaveStatus(401);
    /* Proving the negative: no authorization header was sent at all. */
    expect(response.request.headers.authorization).toBeUndefined();
  });

  /* ================================================================= *
   * STATUS, REDIRECTS AND HEADERS
   * ================================================================= */

  test('an unusual status is reported, not swallowed', async ({ http }) => {
    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .get('/status/418')
      /* The client never throws on status by itself; the test decides what is
       * acceptable. Without this the framework would still return normally —
       * `expectStatus` only controls the *client's* failure path. */
      .expectStatus(418)
      .as('teapot')
      .send();

    expect(response).toHaveStatus(418);
    expect(response.ok).toBe(false);
    expect(response.expectClientError()).toBe(response);
  });

  test('redirects are followed by default and can be asserted instead', async ({ http }) => {
    const client = http.withBaseUrl(PUBLIC_APIS.httpBin);

    /* Followed: the final response is a 200 from the destination. */
    const followed = await client.get('/redirect/2').as('followed redirect').send();
    followed.expectOk();
    expect(followed.url).toContain('/get');

    /* Not followed: the 3xx itself is returned, so its Location can be
     * asserted — which is the only way to test a redirect's target. */
    const notFollowed = await client
      .get('/redirect/1')
      .noRedirect()
      .expectStatus(302)
      .as('unfollowed redirect')
      .send();

    expect(notFollowed).toHaveStatus(302);
    expect(notFollowed).toHaveHeader('location');
  });

  test('default and per-request headers both arrive, with the request winning', async ({
    http,
  }) => {
    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .withHeaders({ 'x-tenant': 'default-tenant' })
      .get('/headers')
      /* Set on the request, overriding the client default of the same name. */
      .header('x-tenant', 'request-tenant')
      .header('x-correlation-id', 'abc-123')
      .as('header precedence')
      .send();

    response.expectOk();
    expect(response.path('headers.X-Tenant'), 'the request header must win').toBe('request-tenant');
    expect(response.path('headers.X-Correlation-Id')).toBe('abc-123');
    /* The framework's own default user agent identifies the suite in server
     * logs, which is worth having when somebody asks who generated traffic. */
    expect(response.path<string>('headers.User-Agent')).toContain('playwright-api-framework');
  });

  test('gzip responses are decoded transparently', async ({ http }) => {
    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .get('/gzip')
      .as('gzip response')
      .send();

    response.expectOk();
    /* If decoding were not transparent, `json()` would throw on the compressed
     * bytes rather than returning a payload. */
    expect(response.path('gzipped')).toBe(true);
  });

  test('a binary response is available as bytes with an intact length', async ({ http }) => {
    const response = await http
      .withBaseUrl(PUBLIC_APIS.httpBin)
      .get('/bytes/{count}')
      .param('count', 2048)
      .as('binary download')
      .send();

    response.expectOk();
    /* The snapshot holds the raw buffer, so a download can be checksummed or
     * length-checked without re-requesting it. */
    expect(response.buffer().byteLength).toBe(2048);
    expect(response.size).toBe(2048);
  });
});
